<option value="">--</option>
<option value=1>Facultad de arquitectura</option>
<option value=2>Programa de Arquitectura</option>
<option value=3>Programa de Diseño Industrial</option>
<option value=4>Especialización en Arquitectura y Urbanismo Bioclimático</option>
<option value=5>Especialización en Gestión de Proyectos de Diseño e Innovación</option>
<option value=6>Maestría en Arquitectura y Urbanismo</option>
<option value=7>Facultad de Ciencias Humanas, Sociales y de la Educación</option>
<option value=8>Programa de Psicología</option>
<option value=9>Programa de Comunicación Social y Periodismo</option>
<option value=10>Programa en Licenciatura en Educación Religiosa</option>
<option value=11>Departamento de Humanidades</option>
<option value=12>Especialización en Pedagogía y Desarrollo Humano</option>
<option value=13>Maestría en Pedagogía y Desarrollo Humano</option>
<option value=14>Maestría en Estudios Culturales</option>
<option value=15>Especialización en Edumática</option>
<option value=16>Especialización en Gerencia de la Comunicación Corporativa</option>
<option value=17>Especialización en Psicología Clínica</option>
<option value=18>Especialización en Intervenciones Psicosociales para la Reducción del Consumo de Sustancias Psicoactivas</option>
<option value=19>Especialización en Psicología Social Comunitaria y Acción Psicosocial</option>
<option value=20>Especialización en Gestión Humana en las Organizaciones</option>
<option value=21>Centro de medios</option>
<option value=22>Facultad de Ciencias Económicas y Administrativas</option>
<option value=23>Programa de Administración de Empresas</option>
<option value=24>Programa de Economía</option>
<option value=25>Programa de Negocios Internacionales</option>
<option value=26>Programa de Mercadeo</option>
<option value=27>Programa de Tecnología en Mercadeo</option>
<option value=28>Tecnología en Gestión de Empresas Agroindustriales</option>
<option value=29>Maestría en Gestión del Desarrollo Regional</option>
<option value=30>Especialización en Finanzas</option>
<option value=31>Especialización en Economía Pública y Gestión Territorial</option>
<option value=32>Especialización Tecnológica en Empresas Agroindustriales</option>
<option value=33>Punto de Bolsa Laboratorio de Econometría y Finanzas/option>
<option value=34>Facultad de Ciencias Básicas e Ingenierías</option>
<option value=35>Programa de Ingeniería Industrial</option>
<option value=36>Programa de Ingeniería de Sistemas y Telecomunicaciones</option>
<option value=37>Programa Tecnología en Desarrollo d Software</option>
<option value=38>Departamento de Ciencias Básicas</option>
<option value=39>Programa Tecnología en Sistemas</option>
<option value=40>Especialización en Desarrollo de Software</option>
<option value=41>Especialización en Producción con Calidad Total</option>
<option value=42>Rectoría</option>
<option value=43>Admisiones y Registro</option>
<option value=44>Centro de Idiomas-Ciuc</option>
<option value=45>Dirección de Investigación e Innovación</option>
<option value=46>Vicerrectoría Académica</option>
<option value=47>Centro de Graduados</option>
<option value=48>Prácticas Académicas</option>
<option value=49>Centro de Innovación Educativa</option>
<option value=50>Bienestar Social</option>
<option value=51>Administración de Empresas</option>
<option value=52>Centro de Familia</option>
<option value=53>Desarrollo Humano</option>
<option value=54>Acompañamiento Académico</option>
<option value=55>Cultura</option>
<option value=56>Deportes</option>
<option value=57>Pastoral</option>
<option value=58>Departamento Financieros</option>
<option value=59>Internacionalización y Relaciones Interinstitucionales</option>
<option value=60>Biblioteca</option>
<option value=61>Centro de Atención Psicológica (CAPSI)</option>
<option value=62>Dirección Administrativa y Financiera</option>
<option value=63>Comunicaciones</option>
<option value=64>Oficina de Mercadeo</option>
<option value=65>Gestión Humana</option>
<option value=66>Gestión Tecnológica</option>
<option value=67>Gestión del Campus</option>
<option value=68>Logística y Servicios Generales</option>
<option value=69>Almacén</option>
<option value=70>Secretaría General</option>
<option value=71>Planeación y Calidad</option>
<option value=72>Proyección Social</option>