<option value="">Programa al que pertenece</option>
<option value=1>Administración de Empresas</option>
<option value=2>Negocios Internacionales</option>
<option value=3>Mercadeo</option>
<option value=4>Tecnología en Gestión de Mercadeo</option>
<option value=5>Maestría en Mercadeo</option>
<option value=6>Maestría en Gestión de Proyectos</option>
<option value=7>Maestría en Gestión del Desarrollo Regional</option>
<option value=8>Maestría en Finanzas</option>
<option value=9>Maestría en Gestión de la Innovación</option>
<option value=10>Especialización en Finanzas</option>
<option value=11>Especialización en Ciberasesoría Financiera</option>
<option value=12>Especialización en Economía Pública y Gestión Territorial</option>
<option value=13>Profesional en Diseño Audiovisual</option>
<option value=14>Arquitectura</option>
<option value=15>Diseño Industrial</option>
<option value=16>Especialización en Gestión de Proyectos e Innovación</option>
<option value=17>Maestría en Arquitectura y Urbanismo</option>
<option value=18>Especialización en Arquitectura Bioclimática</option>
<option value=19>Especialización en Gestión de la Construcción Sostenible</option>
<option value=20>Psicología</option>
<option value=21>Comunicación Social - Periodismo</option>
<option value=22>Licenciatura en Educación Religiosa </option>
<option value=23>Doctorado en Educación en Desarrollo Humano</option>
<option value=24>Maestría en Innovación Educativa</option>
<option value=25>Maestría en Gestión Estratégica de la Comunicación</option>
<option value=26>Maestría en Memoria y Escenarios Transicionales</option>
<option value=27>Maestría en Pedagogía y Desarrollo Humano</option>
<option value=28>Maestría en Estudios Culturales</option>
<option value=29>Especialización en Pedagogía y Desarrollo Humano</option>
<option value=30>Especialización en Edumática Innovación Educativa Mediada por TIC</option>
<option value=31>Especialización en Gerencia de la Comunicación Corporativa</option>
<option value=32>Especialización en Psicología Clínica con énfasis en Psicoterapia con niños y adolescentes</option>
<option value=33>Especialización en Psicología Social Comunitaria y Acción Psicosocial</option>
<option value=34>Especialización en Gestión Humana en las Organizaciones</option>
<option value=35>Ingeniería de Sistemas y Telecomunicaciones</option>
<option value=36>Ingeniería Industrial</option>
<option value=37>Tecnología en Desarrollo de Software</option>
