<option value="">--</option>
<option value=1>Facultad de Arquitectura y Diseño</option>
<option value=2>Arquitectura</option>
<option value=3>Diseño Industrial</option>
<option value=4>Facultad de Ciencias Humanas, Sociales y de la Educación</option>
<option value=5>Comunicación Social - Periodismo</option>
<option value=6>Psicología</option>
<option value=7>Licenciatura en Educación Religiosa</option>
<option value=8>Facultad de Ciencias Económicas y Administrativas</option>
<option value=9>Negocios Internacionales</option>
<option value=10>Administración de empresas</option>
<option value=11>Economía</option>
<option value=12>Mercadeo</option>
<option value=13>Tecnología en Mercadeo</option>
<option value=14>Técnica Profesional en Operación y Logística de Empresas Agroindustriales</option>
<option value=15>Tecnología en Gestión de Empresas Agroindustriales</option>
<option value=16>Facultad de Ciencias Básicas e Ingeniería</option>
<option value=17>Ingeniería de Sistemas y Telecomunicaciones</option>
<option value=18>Ingeniería Industrial</option>
<option value=19>Tecnología en Desarrollo de Software</option>
<option value=20>Maestría en Arquitectura y Urbanismo</option>
<option value=21>Especialización en Arquitectura y Urbanismo Bioclimático</option>
<option value=22>Especialización en Gestión de Proyectos e Innovación</option>
<option value=23>Maestría en Pedagogía y Desarrollo Humano</option>
<option value=24>Maestría en Estudios Culturales</option>
<option value=25>Especialización en Pedagogía y Desarrollo Humano</option>
<option value=26>Especialización en Edumática Innovación de los procesos educativos a través de herramientas multimediales</option>
<option value=27>Especialización en Gerencia de la Comunicación Corporativa</option>
<option value=28>Especialización en Psicología Clínica con énfasis en psicoterapia con niños y adolescentes</option>
<option value=29>Especialización en Intervenciones Psicosociales para la Reducción del Consumo de Sustancias Psicoactivas</option>
<option value=30>Especialización en Psicología Social Comunitaria y Acción Psicosocial</option>
<option value=31>Especialización en Gestión Humana en las Organizaciones</option>
<option value=32>Maestría en Gestión del Desarrollo Regional</option>
<option value=33>Especialización en Finanzas</option>
<option value=34>Especialización en Economía Pública y Gestión Territorial</option>
<option value=35>Especialización Tecnológica en Empresas Agroindustriales</option>
<option value=36>Especialización en Desarrollo del Software</option>
<option value=37>Especialización en Producción con Calidad Total</option>
<option value=38>Departamento de Humanidades</option>
<option value=39>Departamento de Ciencias Básicas</option>
<option value=40>CIUC</option>


