<?php
	        $sql1="SELECT sum(Pre1) as total1 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result1=mysqli_query($cn,$sql1);
			$data1=mysqli_fetch_assoc($result1); 
	        $sql2="SELECT sum(Pre5) as total2 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result2=mysqli_query($cn,$sql2);
			$data2=mysqli_fetch_assoc($result2);
	        $sql3="SELECT sum(Pre9) as total3 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result3=mysqli_query($cn,$sql3);
			$data3=mysqli_fetch_assoc($result3);
	        $sql4="SELECT sum(Pre10) as total4 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result4=mysqli_query($cn,$sql4);
			$data4=mysqli_fetch_assoc($result4);  
	        $sql5="SELECT sum(Pre11) as total5 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result5=mysqli_query($cn,$sql5);
			$data5=mysqli_fetch_assoc($result5); 
	        $sql6="SELECT sum(Pre16) as total6 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result6=mysqli_query($cn,$sql6);
			$data6=mysqli_fetch_assoc($result6); 
	        $sql7="SELECT sum(Pre17) as total7 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result7=mysqli_query($cn,$sql7);
			$data7=mysqli_fetch_assoc($result7);
	        $sql8="SELECT sum(Pre22) as total8 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result8=mysqli_query($cn,$sql8);
			$data8=mysqli_fetch_assoc($result8);
	        $sql9="SELECT sum(Pre26) as total9 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result9=mysqli_query($cn,$sql9);
			$data9=mysqli_fetch_assoc($result9);  
	        $sql10="SELECT sum(Pre27) as total10 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result10=mysqli_query($cn,$sql10);
			$data10=mysqli_fetch_assoc($result10); 
	        $sql11="SELECT sum(Pre32) as total11 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result11=mysqli_query($cn,$sql11);
			$data11=mysqli_fetch_assoc($result11);
	        $sql12="SELECT sum(Pre36) as total12 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result12=mysqli_query($cn,$sql12);
			$data12=mysqli_fetch_assoc($result12);     
            
            $sql13="SELECT sum(Pre2) as total13 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result13=mysqli_query($cn,$sql13);
			$data13=mysqli_fetch_assoc($result13); 
	        $sql14="SELECT sum(Pre3) as total14 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result14=mysqli_query($cn,$sql14);
			$data14=mysqli_fetch_assoc($result14);
	        $sql15="SELECT sum(Pre12) as total15 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result15=mysqli_query($cn,$sql15);
			$data15=mysqli_fetch_assoc($result15);
	        $sql16="SELECT sum(Pre13) as total16 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result16=mysqli_query($cn,$sql16);
			$data16=mysqli_fetch_assoc($result16);  
	        $sql17="SELECT sum(Pre15) as total17 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result17=mysqli_query($cn,$sql17);
			$data17=mysqli_fetch_assoc($result17); 
	        $sql18="SELECT sum(Pre19) as total18 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result18=mysqli_query($cn,$sql18);
			$data18=mysqli_fetch_assoc($result18); 
	        $sql19="SELECT sum(Pre20) as total19 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result19=mysqli_query($cn,$sql19);
			$data19=mysqli_fetch_assoc($result19);
	        $sql20="SELECT sum(Pre23) as total20 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result20=mysqli_query($cn,$sql20);
			$data20=mysqli_fetch_assoc($result20);
	        $sql21="SELECT sum(Pre24) as total21 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result21=mysqli_query($cn,$sql21);
			$data21=mysqli_fetch_assoc($result21);  
	        $sql22="SELECT sum(Pre28) as total22 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result22=mysqli_query($cn,$sql22);
			$data22=mysqli_fetch_assoc($result22); 
	        $sql23="SELECT sum(Pre29) as total23 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result23=mysqli_query($cn,$sql23);
			$data23=mysqli_fetch_assoc($result23);
	        $sql24="SELECT sum(Pre33) as total24 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result24=mysqli_query($cn,$sql24);
			$data24=mysqli_fetch_assoc($result24);  

            $sql25="SELECT sum(Pre4) as total25 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result25=mysqli_query($cn,$sql25);
			$data25=mysqli_fetch_assoc($result25); 
	        $sql26="SELECT sum(Pre6) as total26 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result26=mysqli_query($cn,$sql26);
			$data26=mysqli_fetch_assoc($result26);
	        $sql27="SELECT sum(Pre7) as total27 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result27=mysqli_query($cn,$sql27);
			$data27=mysqli_fetch_assoc($result27);
	        $sql28="SELECT sum(Pre8) as total28 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result28=mysqli_query($cn,$sql28);
			$data28=mysqli_fetch_assoc($result28);  
	        $sql29="SELECT sum(Pre14) as total29 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result29=mysqli_query($cn,$sql29);
			$data29=mysqli_fetch_assoc($result29); 
	        $sql30="SELECT sum(Pre18) as total30 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result30=mysqli_query($cn,$sql30);
			$data30=mysqli_fetch_assoc($result30); 
	        $sql31="SELECT sum(Pre21) as total31 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result31=mysqli_query($cn,$sql31);
			$data31=mysqli_fetch_assoc($result31);
	        $sql32="SELECT sum(Pre25) as total32 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result32=mysqli_query($cn,$sql32);
			$data32=mysqli_fetch_assoc($result32);
	        $sql33="SELECT sum(Pre30) as total33 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result33=mysqli_query($cn,$sql33);
			$data33=mysqli_fetch_assoc($result33);  
	        $sql34="SELECT sum(Pre31) as total34 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result34=mysqli_query($cn,$sql34);
			$data34=mysqli_fetch_assoc($result34); 
	        $sql35="SELECT sum(Pre34) as total35 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result35=mysqli_query($cn,$sql35);
			$data35=mysqli_fetch_assoc($result35);
	        $sql36="SELECT sum(Pre35) as total36 FROM `1.0_Estudiantes` A  WHERE (A.Correo = '$Correo') ";
            $result36=mysqli_query($cn,$sql36);
			$data36=mysqli_fetch_assoc($result36);  
?>